version: '3.8'

services:
  blockscout:
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "ACA"
    restart: always
    container_name: 'blockscout'
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    #command: 'mix phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout-mandala.env
    environment:
      DATABASE_URL: postgresql://postgres:@host.docker.internal:5432/blockscout?ssl=true
      ECTO_USE_SSL: true
    ports:
      - 4000:4000
