version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    #command: ["postgres", "-c", "log_statement=all"]

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "KAR"
    restart: always
    container_name: 'blockscout-karura'
    links:
      - db:database
    #command: 'mix do ecto.create, ecto.migrate, phx.server'
    command: 'mix phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout-karura.env
    ports:
      - 4000:4000
volumes:
  postgres:
