version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    #command: ["postgres", "-c", "log_statement=all"]

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "KAR"
    restart: always
    container_name: 'blockscout-karura'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    #command: 'mix phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      - ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
      - SUBNETWORK=Karura Chain
      - COIN=KAR
      - SUPPORTED_CHAINS='[{"title":"Acala testnet","url":"http://localhost:4000/","test_net?":true},{"title":"Karura testnet","url":"http://localhost:4000/","test_net?":true}]'
      - INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
      - INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
    ports:
      - 4000:4000
volumes:
  postgres:
