version: '3.8'

services:
  blockscout:
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "ACA"
    restart: always
    container_name: 'blockscout-mandala'
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    #command: 'mix phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      - DATABASE_URL=postgresql://postgres:@host.docker.internal:5432/blockscout?ssl=true
      - ECTO_USE_SSL=true
      - ETHEREUM_JSONRPC_HTTP_URL=http://localhost:8545
      - SUBNETWORK=Mandala Chain
      - COIN=ACA
      - SUPPORTED_CHAINS=[{"title":"Mandala testnet","url":"http://localhost:4000/","test_net?":true}]
      - INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
      - INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
    ports:
      - 4000:4000
