version: '3.8'

networks:
  default:
    name: blockscout-mandala

services:
  blockscout-mandala:
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "ACA"
    restart: always
    container_name: 'blockscout-mandala'
    #command: 'mix do ecto.create, ecto.migrate, phx.server'
    command: 'mix phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
      - DATABASE_URL=postgresql://postgres:@host.docker.internal:15432/blockscout
      - ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:18545
      - SUBNETWORK=Mandala Chain
      - COIN=ACA
      - SUPPORTED_CHAINS=[{"title":"Mandala testnet","url":"https://blockscout.mandala.acala.network/","test_net?":true},{"title":"Mandala testnet - subscan","url":"https://acala-testnet.subscan.io/","test_net?":true}]
      - INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
      - INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
      - FIRST_BLOCK=700000
      - TRACE_FIRST_BLOCK=700000
    ports:
      - 4000:4000
